language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Codecov
  - sudo pip install codecov
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install -qq sloccount
  # OCLint
  - ./install_oclint

script: 
  - ./download_other_githubs
  # Console
  - qmake VigenereCipherConsole.pro
  - make debug --silent
  - ./VigenereCipherConsole --key "lemon" --text "helloworld"
  # Build and run the tests
  - qmake VigenereCipherDesktop.pro
  - make debug --silent
  # helgrind
  - valgrind --tool=helgrind --log-file=helgrind.log -v ./VigenereCipherConsole --key "lemon" --text "helloworld"
  - cat helgrind.log
  # memcheck
  - valgrind --leak-check=full -v --show-reachable=yes --log-file=memcheck.log ./VigenereCipherConsole --key "lemon" --text "helloworld"
  - cat memcheck.log
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov
  # Call OCLint
  - ./do_oclint
  # Get my folder
  - my_github=${PWD##*/}  
  # SLOCcount
  - cd ..; sloccount --overhead 1 --personcost 22614 $my_github; cd $my_github

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
